CREATE DATABASE SNOWFLAKE_CLASS_8;
USE DATABASE SNOWFLAKE_CLASS_8;
CREATE SCHEMA SNOW_C_8_SCHEMA;
USE SCHEMA SNOW_C_8_SCHEMA;

CREATE OR REPLACE TABLE AJ_AUTHOR(
    FirstName VARCHAR(25) NOT NULL,
    LastName VARCHAR(35) NOT NULL,
    Street VARCHAR(100) DEFAULT 'Noida',
    City VARCHAR(35) DEFAULT 'Gautam Budh Nagar',
    AuthorState CHAR(2) DEFAULT 'WA',
    Zip CHAR(5),
    Phone VARCHAR(15)
);
