CREATE DATABASE IF NOT EXISTS SNOWFLAKE_CLASS_6;
USE DATABASE SNOWFLAKE_CLASS_6;
CREATE SCHEMA IF NOT EXISTS SNOW_C_6_SCHEMA;
USE SCHEMA SNOW_C_6_SCHEMA;

CREATE OR REPLACE TABLE AGENTS
(
    AGENT_CODE CHAR(6) NOT NULL PRIMARY KEY,
    AGENT_NAME VARCHAR(20),
    WORKING_AREA CHAR(35),
    COMMISSION DECIMAL(10,2),
    PHONE_NO CHAR(15),
    COUNTRY VARCHAR()
);

DESCRIBE TABLE AGENTS;

INSERT INTO AGENTS VALUES ('A007', 'Ramasundar', 'Bangalore', '0.15', '077-25814763', '');
INSERT INTO AGENTS VALUES ('A003', 'Alex ', 'London', '0.13', '075-12458969', '');
INSERT INTO AGENTS VALUES ('A008', 'Alford', 'New York', '0.12', '044-25874365', '');
INSERT INTO AGENTS VALUES ('A011', 'Ravi Kumar', 'Bangalore', '0.15', '077-45625874', '');
INSERT INTO AGENTS VALUES ('A010', 'Santakumar', 'Chennai', '0.14', '007-22388644', '');
INSERT INTO AGENTS VALUES ('A012', 'Lucida', 'San Jose', '0.12', '044-52981425', '');
INSERT INTO AGENTS VALUES ('A005', 'Anderson', 'Brisban', '0.13', '045-21447739', '');
INSERT INTO AGENTS VALUES ('A001', 'Subbarao', 'Bangalore', '0.14', '077-12346674', '');
INSERT INTO AGENTS VALUES ('A002', 'Mukesh', 'Mumbai', '0.11', '029-12358964', '');
INSERT INTO AGENTS VALUES ('A006', 'McDen', 'London', '0.15', '078-22255588', '');
INSERT INTO AGENTS VALUES ('A004', 'Ivan', 'Torento', '0.15', '008-22544166', '');
INSERT INTO AGENTS VALUES ('A009', 'Benjamin', 'Hampshair', '0.11', '008-22536178', '');

SELECT * FROM AGENTS;

SELECT 
MAX(COMMISSION),
MIN(COMMISSION),
SUM(COMMISSION)
FROM AGENTS;

SELECT *
FROM AGENTS 
WHERE PHONE_NO LIKE '044%';

SELECT COUNT(AGENT_CODE)
FROM AGENTS 
WHERE PHONE_NO LIKE '044%';



CREATE OR REPLACE TABLE AJ_CONSUMER_COMPLAINTS
(
    DATE_RECEIVED STRING,
    PRODUCT_NAME VARCHAR(50),
    SUB_PRODUCT VARCHAR(100),
    ISSUE VARCHAR(100),
    SUB_ISSUE VARCHAR(100),
    CONSUMER_COMPLAINT_NARRATIVE STRING,
    COMPANY_PUBLIC_RESPONSE STRING,
    COMPANY VARCHAR(100),
    STATE_NAME CHAR(4),
    ZIP_CODE STRING,
    TAGS VARCHAR(70),
    CONSUMER_CONSENT_PROVIDED CHAR(25),
    SUBMITTED_VIA STRING,
    DATE_SENT_TO_COMPANY STRING,
    COMPANY_RESPONSE_TO_CONSUMER VARCHAR(40),
    TIMELY_RESPONSE CHAR(4),
    CONSUMER_DISPUTED CHAR(4),
    COMPLAINT_ID NUMBER(12,0) NOT NULL PRIMARY KEY
);

SELECT * FROM AJ_CONSUMER_COMPLAINTS;

SELECT MIN(DATE_RECEIVED) AS MIN_DATE, MAX(DATE_RECEIVED) AS MAX_DATE
FROM AJ_CONSUMER_COMPLAINTS;


SELECT
    PRODUCT_NAME,
    COMPANY,
    COUNT(DISTINCT(COMPLAINT_ID)) AS Total_Complaints
FROM AJ_CONSUMER_COMPLAINTS
WHERE SUBMITTED_VIA = 'Phone'
GROUP BY 1,2
HAVING Total_Complaints > 100
ORDER BY 3 DESC;

-- VA CA NY

SELECT  
    STATE_NAME,
    PRODUCT_NAME,
    COMPANY,
    COUNT(DISTINCT(COMPLAINT_ID)) AS Total_complaints
    FROM AJ_CONSUMER_COMPLAINTS
    WHERE STATE_NAME IN('VA','CA','NY') AND SUBMITTED_VIA = 'Phone'
    GROUP BY 1,2,3
    -- HAVING Total_complaints >= 25
    ORDER BY 4 DESC;


    USE DATABASE SNOWFLAKE_SAMPLE_DATA;
    USE SCHEMA TPCDS_SF10TCL;
    SELECT * FROM ITEM LIMIT 1000;

-- EF IS IN BETWEEN THE I_ITEM_ID
     SELECT * 
     FROM ITEM
     WHERE I_ITEM_ID LIKE '%EF%';

     -- I_ITEM_ID START WITH AAAAAAAAEE
     SELECT * 
     FROM ITEM
     WHERE I_ITEM_ID LIKE 'AAAAAAAAEE%';

     -- I_ITEM_ID ENDS WITH GCAAA
     SELECT * 
     FROM ITEM
     WHERE I_ITEM_ID LIKE '%GCAAA';

      SELECT * 
     FROM ITEM
     WHERE I_ITEM_ID LIKE '________EF%';


  

     
     

    
    
