SELECT CURRENT_USER();
SELECT CURRENT_ROLE();
SELECT CURRENT_WAREHOUSE();
SELECT CURRENT_DATABASE();

SHOW ROLES;
USE ROLE {role};

SHOW WAREHOUSES;

USE DATABASE SNOWFLAKE_SAMPLE_DATA;
USE SCHEMA TPCDS_SF10TCL;

SELECT * FROM CUSTOMER LIMIT 100;

-- Also Alter Your default warehouse
ALTER USER{username} SET DEFAULT_WAREHOUSE = {warehousename};

-- Create warehouse
CREATE OR REPLACE WAREHOUSE ANALYTICS
    WITH WAREHOUSE_SIZE = 'X-SMALL'
    MAX_CLUSTER_COUNT = 1
    AUTO_SUSPEND = 300
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

-- However with a sample SQL query you can set whatever timeout you need,Timeout value in second
ALTER WAREHOUSE IF EXISTS {warehouse} SET AUTO_SUSPEND = {second};

ALTER WAREHOUSE IF EXISTS ANALYTICS SET AUTO_SUSPEND = 3600;

-- HOW DO I CREATE NEW DATABASE USER
SHOW ROLES;
USE ROLE ACCOUNTADMIN;
CREATE USER {username} PASSWORD = {password} MUST_CHANGE_PASSWORD = TRUE;


USE DATABASE SNOWFLAKE_SAMPLE_DATA;
USE SCHEMA TPCDS_SF10TCL;

SELECT * FROM CUSTOMER LIMIT 100;


CREATE DATABASE SNOWFLAKE_CLASS_9;
USE DATABASE SNOWFLAKE_CLASS_9;
CREATE SCHEMA SNOW_C_9_SCHEMA;
USE SCHEMA SNOW_C_9_SCHEMA;

-- METHOD-1 HERE ONLY STRUCTURE IS COPIED
CREATE OR REPLACE TABLE CUSTOMERS_COPY LIKE SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.CUSTOMER;
DESCRIBE TABLE CUSTOMERS_COPY;
SELECT * FROM CUSTOMERS_COPY;

CREATE OR REPLACE TABLE CUSTOMER_COPY_M1 CLONE SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.CUSTOMER;
-- SQL compilation error: Cannot clone from a table that was imported from a share.
CREATE OR REPLACE TABLE CUSTOMER_COPY_M1 CLONE AJ_CUSTOMER;

 -- METHOD-2 HERE ENTIRE TABLE IS COPIED
 CREATE OR REPLACE TABLE CUSTOMERS_COPY_M2 AS 
 SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.CUSTOMER LIMIT 1000;

 SELECT * FROM CUSTOMERS_COPY_M2;

 -- COPY ONLY PARTICULAR COLUMN INTO NEW TABLE ALONG WITH PARTICULAR DATA SET
CREATE OR REPLACE TABLE CUSTOMERS_COPY_M3 AS 
SELECT 
    C_CUSTOMER_SK,
    C_CUSTOMER_ID,
    C_BIRTH_YEAR,
    C_FIRST_NAME,
    C_LAST_NAME
FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.CUSTOMER LIMIT 1000;

SELECT * FROM CUSTOMERS_COPY_M3;

-- if i want to structure of any table
SELECT GET_DDL('TABLE','SNOWFLAKE_CLASS_7.SNOW_C_7_SCHEMA.Employee');

-- Difference between alter and update
ALTER Works on Column While UPDATE Works on Row;


 CREATE OR REPLACE TABLE AJ_CUSTOMER
 (
    cust_id INT NOT NULL,
    cust_name VARCHAR(100) NOT NULL,
    cust_address text NOT NULL,
    cust_adhar_number VARCHAR(50) DEFAULT NULL,
    cust_pan_number VARCHAR(50) NOT NULL
 );


 DESCRIBE TABLE AJ_CUSTOMER;

 -- MAKE cust_id as primary key
 ALTER TABLE AJ_CUSTOMER
 ADD PRIMARY KEY(cust_id);
 
 ALTER TABLE AJ_CUSTOMER
 ADD UNIQUE(cust_id);

 ALTER TABLE AJ_CUSTOMER
 ADD COLUMN cust_age INT;

 INSERT INTO AJ_CUSTOMER 
(cust_id, cust_name, cust_address, cust_adhar_number, cust_pan_number, cust_age)
VALUES
(1, 'Amit Sharma', 'Noida Sector 62', '123456789012', 'ABCDE1234F', 30),
(2, 'Neha Verma', 'Delhi Laxmi Nagar', '234567890123', 'FGHIJ5678K', 28),
(3, 'Rahul Singh', 'Gurgaon DLF Phase 3', NULL, 'LMNOP4321Q', 35),
(4, 'Priya Gupta', 'Noida Sector 18', '345678901234', 'QRSTU8765V', 32),
(5, 'Ankit Yadav', 'Ghaziabad Indirapuram', NULL, 'WXYZA1122B', 27),
(6, 'Pooja Mehta', 'Faridabad Sector 15', '456789012345', 'CDEFG3344H', 31),
(7, 'Vikas Jain', 'Jaipur Malviya Nagar', '567890123456', 'HIJKL5566M', 40),
(8, 'Sneha Kapoor', 'Chandigarh Sector 22', NULL, 'NOPQR7788S', 26),
(9, 'Rohit Mishra', 'Lucknow Gomti Nagar', '678901234567', 'TUVWX9900Y', 38),
(10, 'Kavita Singh', 'Patna Boring Road', '789012345678', 'ZABCD1111E', 29),

(11, 'Suresh Kumar', 'Kanpur Kalyanpur', '890123456789', 'EFGHI2222J', 45),
(12, 'Anjali Sharma', 'Delhi Rohini', NULL, 'JKLMN3333K', 33),
(13, 'Deepak Verma', 'Noida Sector 137', '901234567890', 'OPQRS4444L', 36),
(14, 'Nisha Yadav', 'Patna Rajendra Nagar', NULL, 'TUVWX5555M', 25),
(15, 'Manish Gupta', 'Mumbai Andheri', '112233445566', 'YZABC6666N', 42),
(16, 'Ritika Jain', 'Jaipur Vaishali Nagar', '223344556677', 'BCDEF7777P', 34),
(17, 'Ashish Singh', 'Varanasi Lanka', NULL, 'GHIJK8888Q', 37),
(18, 'Simran Kaur', 'Amritsar Ranjit Ave', '334455667788', 'LMNOP9999R', 28),
(19, 'Gaurav Sharma', 'Delhi Dwarka', '445566778899', 'QRSTU0000S', 31),
(20, 'Meena Devi', 'Darbhanga Bihar', NULL, 'VWXYZ1212T', 39);

SELECT * FROM AJ_CUSTOMER;

UPDATE AJ_CUSTOMER 
SET cust_age = 28 WHERE cust_id = 20;

SELECT * FROM AJ_CUSTOMER WHERE cust_adhar_number IS NULL;

DROP COMMAND DELETE THE ENTIRE STRUCTURE OF TABLE;

DROP TABLE AJ_CUSTOMER;
DESCRIBE TABLE AJ_CUSTOMER;
-- QL compilation error: Table 'AJ_CUSTOMER' does not exist or not authorized.
UNDROP TABLE AJ_CUSTOMER;
-- WE CAN RESTORE THE DROP TABLE WITHIN 24 HR ONLY

DELETE FROM AJ_CUSTOMER WHERE cust_id = 20;
